# 실행순서 중요.

services:
  webserver:
    image: hankibeom/market0116:v1
    #   build: 도커파일 경로 (docker build 후에 컨테이너 시작)
    #   docker compose up -d 말고 docker compose up --build
    build: .
    #   docker compose watch : 코드에 변동사항 생기면 컨테이너에 바로 반영
    #   docker compose up -d 말고 docker compose --watch
    #   build 속성이 있어야 develop이 잘 됨
    develop:
      watch:
        #               코드복붙 + 컨테이너 재시작 요청
        - action: sync+restart
          path: .
          target: /app

        #          package.json 파일 변경시 자동으로 docker build
        - action: rebuild
          path: package.json

    ports:
      - 8080:8080
    #   db 먼저 켜달라는 뜻
    depends_on:
      - db
#    networks:
#      - mynet1
#      - mynet2

#  nginx:
#    image: nginx:v1
#    ports:
#      - 80:80
#    networks:
#      - mynet1
#    #  컨테이너 꺼져도 자동 재시작, Docker 엔진 꺼져도 자동 재시작
#    restart: always

  db:
    image: mongo:6.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
#    networks:
#      - mynet2
    volumes:
      - mongo_data:/data/db

  volumes:
    mongo_data:
      external: true

#networks:
#  mynet1:
#  mynet2:
